### ISSUE TITLE
macOS release

### ISSUE THREAD

**Issue by setanarut** [H-Schott/StreamPowerErosion#1]
Is it possible to compile for macOS?

**Comment by H-Schott** [comment]
Hi, although I do not have any macOS to test it, I'm afraid that the OpenGL version we used (one that handles compute shaders) is not supported on macOS.

**Comment by setanarut** [comment]
> Hi, although I do not have any macOS to test it, I'm afraid that the OpenGL version we used (one that handles compute shaders) is not supported on macOS.

:( ok thanks
